### ISSUE TITLE
Want attractive footer for all the pages 

### ISSUE THREAD

**Issue by arunn0909** [arunn0909/BooksWorld#10]
Please provide the screenshot of your work then only I am going to merge in my repo

**Comment by hemantwasthere** [comment]
Hey @arunn0909, I would like to work on this issue

**Comment by arunn0909** [comment]
@hemantwasthere I have already assigned you one task please complete it then only I can assign you the new one. I hope You understand.

**Comment by hemantwasthere** [comment]
I want to work on this one issue 
I have unassigned myself from the previous one

**Comment by arunn0909** [comment]
Ok @hemantwasthere I am assigning this issue to you but its a request that if you don't to work on an issue then don't demand for it.
