### ISSUE TITLE
Sign-up Page 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#101]
So ,  is there any plan to make db as of now or not ? I am thinking to extend dark theme for sign-in/up pages also but as of now these pages are not so useful . 
Also , i can work for the backend part but maybe after some days not now , so should i extend dark theme for these pages or not ?
Demo preview below 
<img width="1440" alt="Screenshot 2022-10-16 at 1 11 14 PM" src="https://user-images.githubusercontent.com/96301800/196024117-5a98b0ff-45ba-4584-a963-25d6ac022db1.png">

One more thing what kind of db are you planning to use ? php-mysql , mongo or what ?

**Comment by arunn0909** [comment]
No issues you can anytime work on it. i was thinking for mongodb

**Comment by arunn0909** [comment]
What do you say

**Comment by AjayMaheshwari23** [comment]
so can i add dark mode for sign-up or not ? because in future we are going to add db right 😌

**Comment by arunn0909** [comment]
Take your call whatever you think is right go for it.👍

**Comment by AjayMaheshwari23** [comment]
ok so i am adding that , Can You assign this issue to me .

**Comment by arunn0909** [comment]
Ya sure
