### ISSUE TITLE
feature: add issue template

### ISSUE THREAD

**Issue by bhattabhi013** [arunn0909/BooksWorld#106]
Add issue template in the project.

**Comment by bhattabhi013** [comment]
I'll like to work on this.

**Comment by arunn0909** [comment]
Go for it

**Comment by zugzwang03** [comment]
Can I work in this issue?

**Comment by zugzwang03** [comment]
@arunn0909

**Comment by arunn0909** [comment]
Go for it merge will be one first come first merge basis 😌👍
