### ISSUE TITLE
Add custom scrollbar

### ISSUE THREAD

**Issue by AnupeshVerma** [arunn0909/BooksWorld#110]
I want to add a custom scrollbar in the website. It will look good and enhances website features

**Comment by AnupeshVerma** [comment]
Please Assign it to me

**Comment by arunn0909** [comment]
You can work on it but you have to provide screenshot of your then only I will merge it .

**Comment by AnupeshVerma** [comment]
please see PR #115 i have added

**Comment by arunn0909** [comment]
screenshot
