### ISSUE TITLE
I want to add attractive header for all pages and add some css for overall better look and feel can I ?

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#15]
In this issue i want to do the following : 
1.) I want to improve the header for all pages .
2.) I forget to remove home button from the "ALL Episodes" page in my 1st PR , so I want to fix that .
3.) Add some CSS for better looks

**Comment by AjayMaheshwari23** [comment]
@arunn0909 can I work on this issue ?

**Comment by arunn0909** [comment]
bro home button is only there in two pages for now which are epage1.html and hpage1.html and this are the required links. Header means navbar please specify it ( like how you can make it better).

**Comment by AjayMaheshwari23** [comment]
Home button is also in  " http://127.0.0.1:5500/hindiComics/hpage1.html "  this page . Should I provide sample navbar images or what ? like the current one looks very basic i want to make it attractive .

**Comment by AjayMaheshwari23** [comment]
I also want to add search box in navbar (if you allow ).

**Comment by arunn0909** [comment]
Add search box @AjayMaheshwari23 i am allowing you but dont remove the home link from hpage1.html and epage1.html. Add search boxes in all the navbar.

**Comment by AjayMaheshwari23** [comment]
okay

**Comment by AjayMaheshwari23** [comment]
I am getting merge conflict while raising the PR , so should i wait till the other person completes the work or  should  i create a PR and you will handle the conflict ?

**Comment by AjayMaheshwari23** [comment]
Can you please review my PR .
