### ISSUE TITLE
I want to make home page more attractive and animated

### ISSUE THREAD

**Issue by Mahekjain2706** [arunn0909/BooksWorld#16]
Basically, I want to add a slider part on the home page and want to make book cards more attractive.

**Comment by Mahekjain2706** [comment]
Hey, Can you please assign me this issue?

**Comment by arunn0909** [comment]
@Mahekjain2706 actually there is slider on the home page I haven't added three different images that's the reason you are not getting it but I am assigning you the task for updating it and now you have to make it more attractive.

**Comment by Mahekjain2706** [comment]
Ok
