### ISSUE TITLE
Add Contact Us Section

### ISSUE THREAD

**Issue by AnkitMajee** [arunn0909/BooksWorld#22]
#### I can section  on the existing page please assign it to me

**Comment by arunn0909** [comment]
someone is already working on the home page so I cant assign it to as of now. @AnkitMajee

**Comment by Mahekjain2706** [comment]
Hey, I want to add the contact us part in the footer, can you assign me?

**Comment by arunn0909** [comment]
@AnkitMajee wana work on this issue or should I assign it to @Mahekjain2706 . Whoever is going to work please make sure that footer must be same in every html file

**Comment by Mahekjain2706** [comment]
Hey, I want to work on it , can you assign it to me ?

**Comment by arunn0909** [comment]
Ok @Mahekjain2706 go for it 😊👍
