### ISSUE TITLE
Adding Favicon/ Icon 

### ISSUE THREAD

**Issue by AnkitMajee** [arunn0909/BooksWorld#23]
### Adding Icon beside the page name will help us relate to which site we are in 

I can design and make a icon of your choice and will Finally add to the page 

#### Please assign the  task to me

**Comment by arunn0909** [comment]
I am assigning this to you You can create on your which you think is better and please provide the screenshot then only I will merge it in my repo. I hope you understand. Happy hacking.

**Comment by AnkitMajee** [comment]
Ok Thank you

**Comment by AnkitMajee** [comment]
### Favicon Icon
![image](https://user-images.githubusercontent.com/76817118/193425096-b5ab4efe-39da-4d96-ab17-2c534ca173e5.png)

**If you approve the above icon which i made on my local page i will pull Request you the file adding it to the html page and saving the Icon to separate file**

**Comment by arunn0909** [comment]
Yeh it is great go with it 👍😊

**Comment by AnkitMajee** [comment]
Ok
