### ISSUE TITLE
I want better card UI for my home screen anyone interested 😊

### ISSUE THREAD

**Issue by arunn0909** [arunn0909/BooksWorld#32]

**Comment by RShalman** [comment]
I can try this one)

**Comment by AjayMaheshwari23** [comment]
I also want to try it 🙂

**Comment by arunn0909** [comment]
Assigning this to you @RShalman because you requested first and @AjayMaheshwari23 you can look for another in

**Comment by arunn0909** [comment]
@RShalman are you working on it or should I assign this to someone else🙄. Please do let me know.

**Comment by RShalman** [comment]
> @RShalman are you working on it or should I assign this to someone else🙄. Please do let me know.

Nope, please re-assign to anyone interested)

**Comment by AjayMaheshwari23** [comment]
I am currently having some running issues assigned in different repo's , so i make take a couple of days in doing this one , @Mahekjain2706 is interested can you assign it to her .

**Comment by arunn0909** [comment]
No issues I will look into this.

**Comment by Mahekjain2706** [comment]
Hey @arunn0909, I want to work on this issue, Can you assign it to me ??

**Comment by arunn0909** [comment]
ya sure
@Mahekjain2706

**Comment by arunn0909** [comment]
@Mahekjain2706 are you working on it.🙄🙄

**Comment by Mahekjain2706** [comment]
Yes , my task is  almost complete , I will do it by today itself.

**Comment by arunn0909** [comment]
ok
