### ISSUE TITLE
Fixing Favicon / title in every page

### ISSUE THREAD

**Issue by AnkitMajee** [arunn0909/BooksWorld#33]
# Found another issue
 The favicon is not showing in `https://arunn0909.github.io/BooksWorld/englishComics/english.html` and also on `https://arunn0909.github.io/BooksWorld/hindiComics/hindi.html`  the title page of both the comics section is not changing it still showing Home page we can   easily divide it into three title name 

1. **Home page | Books World**
2. **English Comics | Books World**
3. **Hindi Comics | Books World**

 ### please assign it to me

**Comment by arunn0909** [comment]
Go for it 👍

**Comment by AnkitMajee** [comment]
ok
