### ISSUE TITLE
Dark Mode Feature 🌙 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#34]
Some users prefer viewing the website in dark more for better readability so can I add a button to toggle between Dark and light mode . Can i ?

**Comment by arunn0909** [comment]
What about dark mode feature 🥲

**Comment by AjayMaheshwari23** [comment]
Why not , but a button should be there for switching between light ( by  default look ) and dark mode , right ?

**Comment by arunn0909** [comment]
Okay work on it but with button I want that dark mode feature in it . All the best 😊👍

**Comment by AjayMaheshwari23** [comment]
Sure
