### ISSUE TITLE
I want to improve the design of buttons .

### ISSUE THREAD

**Issue by RhyshaKachari** [arunn0909/BooksWorld#38]
I want make the buttons look more attractive in the project.

**Comment by RhyshaKachari** [comment]
Kindly assign me this issue :)

**Comment by arunn0909** [comment]
@RhyshaKachari are you working on it bro 🙄

**Comment by RhyshaKachari** [comment]
@arunn0909 yes I am working on it. I will finish it by today.

**Comment by arunn0909** [comment]
Ok great👍
