### ISSUE TITLE
i would like to add a new "interests" cards section after carousel/slider

### ISSUE THREAD

**Issue by amansgith** [arunn0909/BooksWorld#40]
please assign this task to me

**Comment by arunn0909** [comment]
can you please elaborate more like what is this section for 🙄

**Comment by amansgith** [comment]
it will contain cards with titles like "fiction", "fantasy", "romance", "horror".. etc. and images also

**Comment by arunn0909** [comment]
ok go  for it but please make sure that that cards looks good and one more thing please provide screenshot of you work after yo are done.

**Comment by amansgith** [comment]
yes sure :)

**Comment by arunn0909** [comment]
happy hacking 👍😉

**Comment by amansgith** [comment]
so here is the little work from my side 😊
<img width="960" alt="section" src="https://user-images.githubusercontent.com/104363876/193606322-933b0df5-ba5f-4559-9174-852fb74ac88f.png">

**Comment by amansgith** [comment]
the blue color in "horror" text is due to anchor tag.. which i will remove

**Comment by amansgith** [comment]
hi i want to add some hovering effects to the cards of genre section to make it look good
