### ISSUE TITLE
Just want to confirm is this repo not a part of Hactoberfest and also can I add images of books in books pages .

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#5]
[](url)

**Comment by AjayMaheshwari23** [comment]
I don't know how to message you directly @arunn0909 so i created this issue to ask what i stated in this issue .

**Comment by arunn0909** [comment]
Actually this is my first time participating as a maintainer I have done all the required things but I am not sure from where I can check that this repo is a part of fest or not . Comming to Issue I am assigning it to you. Happy learning.👍

**Comment by AjayMaheshwari23** [comment]
ok i guess you need to give my PR Hactoberfest-accepted label

**Comment by AjayMaheshwari23** [comment]
On their Website they have mentioned , Maintainers need to provide Hactoberfest-accepted label to contributor's PR and the PR should not be closed .

**Comment by arunn0909** [comment]
After merging the pr we have to close it because last year i participated as a contributer and they are doing the same thing

**Comment by arunn0909** [comment]
And I have added hactoberfest- accepted label on your PR's as well.

**Comment by AjayMaheshwari23** [comment]
Ohk no issues i just want to learn how to contribute to open source . Be ready for reviewing my next PR in 20-30 mins 🙃

**Comment by arunn0909** [comment]
For  sure 😊
