### ISSUE TITLE
Footer Design is good but it is not responsive anyone wants to work on it.

### ISSUE THREAD

**Issue by arunn0909** [arunn0909/BooksWorld#51]
You have to attach screenshot of your Work.

**Comment by Chaitanya-087** [comment]
i would like to work on it

**Comment by rashmisubhash** [comment]
Can I take it up?

**Comment by arunn0909** [comment]
@Chaitanya-087 assigning this to you.

**Comment by arunn0909** [comment]
@rashmisubhash I have one more issue would you like to work on it.🙄

**Comment by rashmisubhash** [comment]
Sure

**Comment by Chaitanya-087** [comment]
![image](https://user-images.githubusercontent.com/76115770/193836071-90f7d47d-019b-4814-90ba-fc0048d702b1.png)

**Comment by Chaitanya-087** [comment]
![image](https://user-images.githubusercontent.com/76115770/193836338-6d8cb710-4e93-4a85-b4a4-901b0c02d299.png)

**Comment by arunn0909** [comment]
@rashmisubhash I have raised one issue #54 you can work on it if you want 😊👍

**Comment by rashmisubhash** [comment]
I see that it is already assigned 😄

**Comment by arunn0909** [comment]
@rashmisubhash #54 it is not assigned for now.
