### ISSUE TITLE
Looking for login and sign up page along with the navbar link.

### ISSUE THREAD

**Issue by arunn0909** [arunn0909/BooksWorld#6]
Design of the page must be appealing and colour selection must be to the point.

**Comment by hemantwasthere** [comment]
Can I work on this issue

**Comment by pantheism2709** [comment]
I want to work on this issue Please assign it to me @arunn0909

**Comment by arunn0909** [comment]
@sachin2709 i am assigning this issue to you . Please provide the screenshot once you are done that I want to see first that what you have made.

**Comment by pantheism2709** [comment]
Sure @arunn0909

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by pantheism2709** [comment]
![Screenshot (4015)](https://user-images.githubusercontent.com/96466673/193406515-5f9f5871-31d2-4e0c-818e-098234edbb3a.png)
![Screenshot (4016)](https://user-images.githubusercontent.com/96466673/193406518-cbae5c5f-aa5f-49dc-89c9-2432b8989003.png)


I have made login and signup, i want little discription about where and how i need to add navbar link @arunsingh009

**Comment by arunn0909** [comment]
bro it is good you just have to do this . Create One folder components and then add this file to that folder after that commit it rest I will update it in my navbar and thanks for giving your time.

**Comment by arunn0909** [comment]
> Hello, Im interested in working on this. Please assign me this issue.

@samyaksand bro you can work on other issues or create your own actually i already have assigned this to @sachin2709

**Comment by arunn0909** [comment]
> Hello, Im interested in working on this. Please assign me this issue.

@samyaksand bro you can work on other issues or create your own actually i already have assigned this to @sachin2709

**Comment by arunn0909** [comment]
> Hello, Im interested in working on this. Please assign me this issue.

@samyaksand bro you can work on other issues or create your own actually i already have assigned this to @sachin2709
