### ISSUE TITLE
I want that this blue outline will not appear on the buttons when user hovers on it. Anyone intrested.

### ISSUE THREAD

**Issue by arunn0909** [arunn0909/BooksWorld#61]
![error](https://user-images.githubusercontent.com/114744225/194002203-bf4d9ac5-f81c-4203-b628-eb4f01d26146.png)
you have to upload the screenshot of your work.

**Comment by amanchoudhary18** [comment]
I can work on this

**Comment by arunn0909** [comment]
yes go for it.

**Comment by amanchoudhary18** [comment]
It is working fine in mine.
![image](https://user-images.githubusercontent.com/63499156/194006132-d5fbecd3-a8d9-48ac-b48b-425b4b906735.png)

**Comment by arunn0909** [comment]
try to press it once

**Comment by amanchoudhary18** [comment]
Okay so you want to remove the outline completely ?

**Comment by arunsingh009** [comment]
Yes
