### ISSUE TITLE
Edit Readme.md

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#67]
I want to make the following changes :- 
1.) Books World Logo is not visible because of black colour , so i will fix that . (see attached image)
<img width="918" alt="Screenshot 2022-10-06 at 2 48 07 AM" src="https://user-images.githubusercontent.com/96301800/194165895-a9a47993-f342-4a78-8f5f-e5b84f8102c3.png">

2.) I want to add Hactoberfest 2022 image in readme to attract more contributors   (see attached image) , as many contributors remain confused whether this repo is part of fest or not . 
<img width="921" alt="Screenshot 2022-10-06 at 2 51 59 AM" src="https://user-images.githubusercontent.com/96301800/194166294-29e9c911-28c3-4d38-8eaf-cb53c241aba1.png">

3.) I want to mention a message saying "Do star the repo" so that reach of this repo will increase .   (see attached image) 
<img width="832" alt="Screenshot 2022-10-06 at 2 53 36 AM" src="https://user-images.githubusercontent.com/96301800/194166580-bab4b8ad-9521-45be-816b-9f58116620c0.png">

Can you assign it to me ?

**Comment by arunn0909** [comment]
ya go for it 😉👍
