### ISSUE TITLE
There is no button to swich dark mode on/off for the english & hindi comics page

### ISSUE THREAD

**Issue by moreharsh** [arunn0909/BooksWorld#69]
![image](https://user-images.githubusercontent.com/60495873/194238124-69a381fe-a048-4369-a43d-fc02cf3808c0.png)

**Comment by arunn0909** [comment]
bro I dont't think that there are dark mode button on every page I think if user selected that dark mode feature it must be applied to al the other pages.

**Comment by arunn0909** [comment]
If you want to work on that feature without adding extra button then I can assign this issue to you.

**Comment by moreharsh** [comment]
> bro I dont't think that there are dark mode button on every page I think if user selected that dark mode feature it must be applied to al the other pages.

Actually, if you select the dark mode on the home page, and go to any other page, then the dark mode disappears. 
And even the dark mode isn't retained for the home page if you visit it back from some other page.

**Comment by moreharsh** [comment]
> > bro I dont't think that there are dark mode button on every page I think if user selected that dark mode feature it must be applied to al the other pages.
> 
> Actually, if you select the dark mode on the home page, and go to any other page, then the dark mode disappears. And even the dark mode isn't retained for the home page if you visit it back from some other page.

maybe that's a bug

**Comment by moreharsh** [comment]
Right now, the code is only updating the theme of the home page. I think we should make use of the cookies/ session storage to store the theme. So that the dark mode will be retained throughout the website and not just for that specific page.

**Comment by arunn0909** [comment]
So I am assigning this to you 👍😊

**Comment by moreharsh** [comment]
I have made some changes to the previous code and created a new pull request.
Pull request #75
