### ISSUE TITLE
Add smooth transition on icon while hover icons

### ISSUE THREAD

**Issue by AnshuPathak-88825** [arunn0909/BooksWorld#72]
![image](https://user-images.githubusercontent.com/78332454/194337925-b89930ce-2b92-4292-ad7b-774cba93a8d5.png)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue @arunn0909

**Comment by AnshuPathak-88825** [comment]
with hacktoberfest label

**Comment by arunn0909** [comment]
Bro which icons you are talking about can you please elaborate

**Comment by AnshuPathak-88825** [comment]
socials

**Comment by arunn0909** [comment]
Ok go for it and please mention in comments what you have done by mentioning images or a short video clip

**Comment by AnshuPathak-88825** [comment]
pls merge my pr
