### ISSUE TITLE
Add contact page 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [arunn0909/BooksWorld#73]
![image](https://user-images.githubusercontent.com/78332454/194349738-e4a7f690-5ee8-42eb-b1cb-86d3b5eb9b93.png)
I wanna add contact page like this

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by arunn0909** [comment]
Bro we don't need one that's why I haven't raised the issue yet 😌

**Comment by AnshuPathak-88825** [comment]
ok
