### ISSUE TITLE
Add contributor image in readme file

### ISSUE THREAD

**Issue by AnshuPathak-88825** [arunn0909/BooksWorld#81]

**Comment by Ankurrawat-12** [comment]
assign me this issue, i would like to work on this.

**Comment by arunn0909** [comment]
Ya go for it 👍 and provide me the screenshot after you are done with your work

**Comment by Ankurrawat-12** [comment]
ok

**Comment by Ankurrawat-12** [comment]
Done

**Comment by Ankurrawat-12** [comment]
![image](https://user-images.githubusercontent.com/78417225/194617023-518f28f6-f28c-4765-8b83-782519fc17b0.png)
![image](https://user-images.githubusercontent.com/78417225/194617044-40c492a0-e502-4b0a-8d97-061e16857c00.png)

**Comment by Ankurrawat-12** [comment]
@arunn0909 Here are the screenshots.

**Comment by AnshuPathak-88825** [comment]
Good work

**Comment by Ankurrawat-12** [comment]
thanks man

**Comment by Ankurrawat-12** [comment]
@arunn0909  please merge my pr
