### ISSUE TITLE
Auto Dismiss the alert 

### ISSUE THREAD

**Issue by Hariom8799** [arunn0909/BooksWorld#83]

**Comment by Hariom8799** [comment]
pls assign me this issue @arunn0909

**Comment by Hariom8799** [comment]
![Capture](https://user-images.githubusercontent.com/76242202/194599370-0eed03bd-01d3-4f8e-899e-fee9bf59995d.PNG)
the alert which is on the homepage is not dismissing automatically

**Comment by arunn0909** [comment]
Ok you can work on it 👍

**Comment by arunn0909** [comment]
Please provide a short clip when you are done 👍

**Comment by Hariom8799** [comment]
done

**Comment by Hariom8799** [comment]
By adding this feature to your website, the alert is dismissed automatically after 3 second
