### ISSUE TITLE
Add link in social icons

### ISSUE THREAD

**Issue by AnshuPathak-88825** [arunn0909/BooksWorld#95]
![image](https://user-images.githubusercontent.com/78332454/195156103-4bf06669-a48b-4740-b9ba-f77709de0bcb.png)

**Comment by RiaMalvi** [comment]
Can you please assign me this issue?

**Comment by arunn0909** [comment]
go for it @RiaMalvi

**Comment by RiaMalvi** [comment]
Kindly provide me with your Facebook, LinkedIn, Twitter, Instagram, and Youtube links that need to be added to the icon.

**Comment by arunn0909** [comment]
Just add anchor tags there i will merge it

**Comment by RiaMalvi** [comment]
The anchor tags are already present there.

**Comment by arunn0909** [comment]
Actually i don't have social links right now so I am closing this issue
