### ISSUE TITLE
Fix Dark Mode in some page 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#97]
hey arun , whats up ! 
when we are switching to dark mode it is not getting applied to hpage.html and epage.html , Even though dark mode is selected in cookie it is not showing its effect so can i fix that up ?
<img width="1440" alt="Screenshot 2022-10-16 at 11 04 10 AM" src="https://user-images.githubusercontent.com/96301800/196019906-a588e6fa-3db5-4404-afd1-9d776357a83d.png">

**Comment by arunn0909** [comment]
Go on sir 🙏👍

**Comment by AjayMaheshwari23** [comment]
Also , this sign in button turning blue and showing underline on hover is not looking cool , so i am fixing that up .
<img width="518" alt="Screenshot 2022-10-16 at 11 34 43 AM" src="https://user-images.githubusercontent.com/96301800/196020811-b75ece1a-69da-411d-899e-4878d0e6fdf2.png">

**Comment by AjayMaheshwari23** [comment]
you have closed this , should I create new issue for this then ?
