### ISSUE TITLE
Fixing Sign-in button 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [arunn0909/BooksWorld#99]
sign in button turning blue and showing underline on hover is not looking cool , so can i am fix that up ?
<img width="518" alt="Screenshot 2022-10-16 at 11 58 23 AM" src="https://user-images.githubusercontent.com/96301800/196021561-32f03d95-1874-4991-9c9d-81adaacd468f.png">

**Comment by arunn0909** [comment]
Go for it 👍

**Comment by AjayMaheshwari23** [comment]
Also , is no database connected yet , i am trying to sign up , but it is not working ?

**Comment by arunn0909** [comment]
No db till now
